apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: {{ .Values.appProject }}
  namespace: {{ .Values.const.argoNS }}

spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  destinations:
  - namespace: '*'
    server: '*'

  sourceRepos:
  - '*'