apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:''
  policy.csv: |
    p, role:builder-user-role, projects, get, *, allow
    p, role:builder-user-role, applications, *, *, allow
    p, role:builder-user-role, repositories, *, *, allow        
    p, role:builder-user-role, exec, create, *, allow
    g, builderuser, role:builder-user-role