apiVersion: v2
name: azure-pipelines-agent-generic
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: azdo-agent-library-chart
    version: 0.1.0
    repository: file://../azdo-agent-library-chart