{{- define "azdo-agent-library-chart.service-account" -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::704909879244:role/AzureAgentAccess
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true        

{{- end -}}