apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-runner
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - pods
      - pods/log  
      - configmaps    
      - secrets
      - serviceaccounts
    verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]    