apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-secrets

spec:
  destination:    
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'

  source:    
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.6.1
    chart: external-secrets
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: {{ .Values.general.serviceAccountRole }}          

  project: tools

  syncPolicy:  
    automated: {}
    syncOptions:
      - CreateNamespace=true