apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: eso-secrets
  namespace: {{ .Values.const.argoNS }}
  finalizers:
  - {{ .Values.const.finalizers }}

spec:
  project: {{ .Values.appProject }}
  
  source:
    path: "{{ .Values.appProject }}/templates/eso-secrets"
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.general.clusterName }}
  
  destination:
    server: {{ .Values.const.server }}
    namespace: {{ .Values.appProject }} 

  syncPolicy:
    automated:
      selfHeal: true    